### ISSUE TITLE
yt-dlg User Id Issue

### ISSUE THREAD

**Issue by khoi16ngo** [oleksis/youtube-dl-gui#124] opened 2023-02-22 07:05 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

```
2023-02-21 23:25:02,693-DEBUG-Worker_1-ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2023-02-21 23:25:02,694-DEBUG-Worker_1-Child process exited with non-zero code: 1
2023-02-21 23:57:54,174-DEBUG-Worker_1-ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2023-02-21 23:57:54,175-DEBUG-Worker_1-Child process exited with non-zero code: 1
```

#### What operating system do you use ?
Windows 11

#### List of actions to perform to reproduce the problem:

  1. paste url into top field
  2. click add
  3. click download

#### What is the expected behaviour ?
Should download the video in specified format

#### What happens instead ?
Nothing downloads. I have seen this error on the official yt-dlg git hub and they fixed it in a release but I'm not sure how to get the new version of it and connect it to this GUI. The issue comes from the the user id can now have an @ symbol. I think the issue is fixed but I updated the GUI to the lastest version and looks like the user id issue is still there.

**Comment by oleksis** [comment] 2023-02-22 07:49
Update to the latest `yt-dlp` CLI Backend. See https://github.com/yt-dlg/yt-dlg/issues/11#issuecomment-1436003375

**Comment by khoi16ngo** [comment] 2023-02-23 00:04
I am on yt-dlg 1.8.4 and i clicked update, but it still shows up this error and I cannot download.

**Comment by khoi16ngo** [comment] 2023-02-23 00:08
looks like it works when I changed the CLI backend from `youtube-dlp.exe` to `yt-dlp.exe`

**Comment by oleksis** [comment] 2023-02-23 00:23
If the issue is complete as fixed, please feel free to close it.

**Comment by khoi16ngo** [comment] 2023-02-23 00:37
Ah ok, I think the issue is resolved now. Sorry about that I think I just had to play around with the settings with the new update. Thanks for the help.

**Closed** 2023-02-23 00:37 UTC
Labels: duplicate

**Comment by VaelophisNyx** [comment] 2023-08-25 23:03
Getting this issue on the most recent release now

**Comment by oleksis** [comment] 2023-08-25 23:11
@VaelophisNyx can share the URL , steps or logs the issue you having?

**Comment by VaelophisNyx** [comment] 2023-08-26 01:44
https://www.youtube.com/watch?v=ZBJA9lPi4gs URL in question
steps are just add, set to convert to mp3, download
log is just the exact same error in the original issue post

**Comment by VaelophisNyx** [comment] 2023-08-26 01:45
I think it may be that this video is trying to download as a WebM and convert from that

**Comment by oleksis** [comment] 2023-08-26 01:57
@VaelophisNyx for Post-Processing Video or Audio you need FFmpeg: https://yt-dlg.github.io/yt-dlg/Install-FFmpeg-on-Windows.html

**Comment by VaelophisNyx** [comment] 2023-08-26 02:48
I should state it's worked fine up to today, I have FFmpeg. It just died when I tried it today
